# Generated by Django 5.2.14 on 2026-05-24 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('tipo', models.CharField(choices=[('MANUAL', 'Caja manual Choco'), ('AUTO', 'Autoservicio'), ('WEB', 'Venta online')], max_length=10)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('categoria', models.CharField(blank=True, max_length=60)),
                ('codigo_vaso', models.CharField(blank=True, help_text='Código normal usado cuando se entrega con vaso.', max_length=20)),
                ('codigo_botella', models.CharField(blank=True, help_text='Código que debe ingresarse si se entrega con botella.', max_length=20)),
                ('descripcion_vaso', models.CharField(blank=True, max_length=240)),
                ('descripcion_botella', models.CharField(blank=True, max_length=240)),
                ('convertible', models.BooleanField(default=False, help_text='Permite transformar automáticamente vaso → botella.')),
                ('confirmado', models.BooleanField(default=False, help_text='Marcar cuando los códigos han sido validados con el negocio.')),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jornadas', to='ventas.caja')),
            ],
            options={
                'ordering': ['-fecha', 'caja__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Orden del cierre dentro del día: 1, 2, 3...')),
                ('modalidad_periodo', models.CharField(choices=[('VASO', 'Venta normal: mantener vaso'), ('BOTELLA', 'Entrega con botella: convertir productos aplicables')], default='VASO', help_text='Presentación entregada en las ventas ocurridas desde el cierre anterior hasta este cierre.', max_length=12)),
                ('motivo_cambio', models.CharField(blank=True, help_text='Ejemplo: agotamiento de jarabe.', max_length=180)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cierres/%Y/%m/%d/')),
                ('ocr_texto', models.TextField(blank=True)),
                ('ocr_estado', models.CharField(blank=True, max_length=240)),
                ('confirmado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres', to='ventas.jornada')),
                ('productos_convertir', models.ManyToManyField(blank=True, help_text='Opcional: si se deja vacío, se convierten todos los productos convertibles del periodo botella.', related_name='cierres_convertidos', to='ventas.producto')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_leido', models.CharField(max_length=20)),
                ('cantidad_acumulada', models.PositiveIntegerField()),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.cierre')),
            ],
            options={
                'ordering': ['codigo_leido'],
                'constraints': [models.UniqueConstraint(fields=('cierre', 'codigo_leido'), name='codigo_unico_por_cierre')],
            },
        ),
        migrations.AddConstraint(
            model_name='jornada',
            constraint=models.UniqueConstraint(fields=('fecha', 'caja'), name='jornada_unica_por_caja_fecha'),
        ),
        migrations.AddConstraint(
            model_name='cierre',
            constraint=models.UniqueConstraint(fields=('jornada', 'numero'), name='numero_cierre_unico_en_jornada'),
        ),
    ]
